In [3]:
%pip install pyarrow


   ---------------------------------------- 0.0/25.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/25.3 MB ? eta -:--:--
   ---------------------------------------- 0.1/25.3 MB 825.8 kB/s eta 0:00:31
    --------------------------------------- 0.4/25.3 MB 3.5 MB/s eta 0:00:08
   - -------------------------------------- 0.9/25.3 MB 5.5 MB/s eta 0:00:05
   -- ------------------------------------- 1.4/25.3 MB 6.7 MB/s eta 0:00:04
   -- ------------------------------------- 1.9/25.3 MB 7.5 MB/s eta 0:00:04
   --- ------------------------------------ 2.3/25.3 MB 8.1 MB/s eta 0:00:03
   ---- ----------------------------------- 2.7/25.3 MB 8.3 MB/s eta 0:00:03
   ----- ---------------------------------- 3.3/25.3 MB 8.7 MB/s eta 0:00:03
   ----- ---------------------------------- 3.8/25.3 MB 9.3 MB/s eta 0:00:03
   ------ --------------------------------- 4.2/25.3 MB 9.3 MB/s eta 0:00:03
   ------- -------------------------------- 4.8/25.3 MB 9.5 MB/s eta 0:00:03
   -------

In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Tensor = torch.tensor([[[1,2,3],[1,2,3],[1,2,4],]])
Tensor


tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 4]]])

In [5]:
print(Tensor.shape)
print(Tensor[0])


torch.Size([1, 3, 3])
tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 4]])


In [13]:
#random 
rand_torch = torch.rand(3,4)
range_torch = torch.arange(3,6)
print(rand_torch,range_torch)

#random with image size
rand_img_torch = torch.rand(size=(224,224,3))
print(rand_img_torch.ndim) 

#torch zeros
zero_torch = torch.zeros(size=(3,4))
print(zero_torch)
one_torch = torch.ones(size=(4,3))
print(one_torch)
print(one_torch.T)

zero_like_torch = torch.zeros_like(torch.arange(1,10,1))
print(zero_like_torch)

tensor([[0.6637, 0.5922, 0.5477, 0.8690],
        [0.1205, 0.9501, 0.1540, 0.3778],
        [0.9061, 0.9813, 0.0986, 0.4943]]) tensor([3, 4, 5])
3
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])


In [18]:
#파라미터 설정
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=torch.float32,device="cuda",requires_grad=False)
float_16_tensor = float_32_tensor.type(torch.float16)
int_32_tensor = float_16_tensor.type(torch.int32)
long_32_tensor = float_16_tensor.type(torch.long)
print(float_32_tensor)
print(float_32_tensor*float_16_tensor)
print(int_32_tensor)
print(int_32_tensor * float_32_tensor)
print(float_32_tensor * long_32_tensor)
#데이터 타입에 유의
#Tensors not right datatype => tensor 안 element의 정보를 얻으려면, tensor.dtype에 접근해야함.
#Tensors not right shape
#Tensors not on right device.

tensor([3., 6., 9.], device='cuda:0')
tensor([ 9., 36., 81.], device='cuda:0')
tensor([3, 6, 9], device='cuda:0', dtype=torch.int32)
tensor([ 9., 36., 81.], device='cuda:0')
tensor([ 9., 36., 81.], device='cuda:0')


In [24]:
some_tensor = torch.rand(3)
some_tensor+=10
some_tensor*=2
print(some_tensor.device)

sample_tensor = torch.arange(1,4)
#torch 행렬곱(elementwise)
print(sample_tensor ,"*" ,sample_tensor)
print(f"Equals : {sample_tensor * sample_tensor}")



# torch 행렬곱 (dot) 1x1 + 2x2 + 3x3
print(f"dot : {torch.matmul(sample_tensor,sample_tensor)}")


cpu
tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals : tensor([1, 4, 9])
dot : 14


In [23]:
%%time
value = 0 
for i in range(len(sample_tensor)):
    value += sample_tensor[i] * sample_tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 2 ms


In [25]:
%%time
print(torch.matmul(sample_tensor,sample_tensor))

#반복문보다 내장 함수가 훨씬 빠르다.
#행렬곱은 안쪽의 디멘션이 같아야함.
#(3,2)(2,3) / (1,6),(6,1)이어야한다는 이야기.
#딥러닝할때 shape에는 에러가 계속 난다.


tensor(14)
CPU times: total: 0 ns
Wall time: 0 ns


In [37]:
tensor_A = torch.arange(1,7).reshape(3,-1)
tensor_B = torch.arange(7,13).reshape(3,-1) 
print(torch.matmul(tensor_A ,tensor_B.T))
#dot only for 1d dimension
print(tensor_A @ tensor_B.T)
print(tensor_A * tensor_B)



tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])
tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])
tensor([[ 7, 16],
        [27, 40],
        [55, 72]])


In [41]:
x= torch.arange(0,100,step =10,dtype=torch.float32)
#dtype이 무조건 float32이여야한다.
torch.mean(x)
torch.argmax(x)
torch.argmin(x)

tensor(9)

In [53]:
#Reshape : 정수 넣은 순서대로 재배열
#View 특정 torch를 바라보는 torch 생성.
#stacking vstack, hstack
#squeeze 1 dimension을 모두 지운다.
#unsqueeze 1 dimension을 추가한다.
#permute : view를 반환한다.
y= torch.arange(1,10)
y.reshape(1,9)
print(y)
z= y.view(1,9)
z[0][4]=13
print(y)

x_vstack = torch.vstack([y,y,y,y,y,])
x_hstack = torch.hstack([y,y,y,y,y,])
print(x_vstack)
print(x_hstack)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([ 1,  2,  3,  4, 13,  6,  7,  8,  9])
tensor([[ 1,  2,  3,  4, 13,  6,  7,  8,  9],
        [ 1,  2,  3,  4, 13,  6,  7,  8,  9],
        [ 1,  2,  3,  4, 13,  6,  7,  8,  9],
        [ 1,  2,  3,  4, 13,  6,  7,  8,  9],
        [ 1,  2,  3,  4, 13,  6,  7,  8,  9]])
tensor([ 1,  2,  3,  4, 13,  6,  7,  8,  9,  1,  2,  3,  4, 13,  6,  7,  8,  9,
         1,  2,  3,  4, 13,  6,  7,  8,  9,  1,  2,  3,  4, 13,  6,  7,  8,  9,
         1,  2,  3,  4, 13,  6,  7,  8,  9])


In [57]:
#squeeze
# 크기가 1인 디멘션을 제거한다.
k = torch.arange(0,72).reshape(2,3,1,3,2,-1)
print(k.squeeze().shape)

#크가기 1인 디멘션을 추가한다.
k_unsqueeze = k.unsqueeze(dim=0)
print(k_unsqueeze.shape)
k_unsqueeze = k_unsqueeze.unsqueeze(dim=3)
print(k_unsqueeze.shape)


torch.Size([2, 3, 3, 2, 2])
torch.Size([1, 2, 3, 1, 3, 2, 2])
torch.Size([1, 2, 3, 1, 1, 3, 2, 2])


In [58]:
#permute 순서를 바꿀수 있다.
x_original = torch.rand(size=(224,224,3))
x_permuted = x_original.permute(2,0,1)  # 인덱스로 차원을 바꾼다. 2->0, 1->2 0->1
print(x_original.shape,x_permuted.shape) #contiguous() 써도 됨(메모리)

torch.Size([224, 224, 3]) torch.Size([3, 224, 224])
