In [4]:
import torch 
print(torch.cuda.is_available())
x= torch.ones(5)
#start
y= torch.zeros(3)
w = torch.randn(5,3,requires_grad = True)
#bias
b= torch.randn(3,requires_grad=True)
z= torch.matmul(x,w)+b

loss = torch.nn.functional.binary_cross_entropy_with_logits(z,y)
print(z,y)
print(loss)

True
tensor([-1.6333,  1.4818,  0.5686], grad_fn=<AddBackward0>) tensor([0., 0., 0.])
tensor(0.9608, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)


In [2]:
print(w.grad)
print(b.grad)
loss.backward(retain_graph=True)
print(w.grad)
print(b.grad)

None
None
tensor([[0.2822, 0.0213, 0.2398],
        [0.2822, 0.0213, 0.2398],
        [0.2822, 0.0213, 0.2398],
        [0.2822, 0.0213, 0.2398],
        [0.2822, 0.0213, 0.2398]])
tensor([0.2822, 0.0213, 0.2398])


In [3]:
z= torch.matmul(x,w)+b
print(z.requires_grad)

with torch.no_grad():
    z= torch.matmul(x,w)+b
    print(z.requires_grad)

True
False
