In [2]:
%pip install numpy


     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ------------------------- ------------ 41.0/61.0 kB 991.0 kB/s eta 0:00:01
     ---------------------------------------- 61.0/61.0 kB 1.1 MB/s eta 0:00:00
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
    --------------------------------------- 0.3/15.5 MB 7.0 MB/s eta 0:00:03
   -- ------------------------------------- 0.8/15.5 MB 8.8 MB/s eta 0:00:02
   --- ------------------------------------ 1.4/15.5 MB 9.7 MB/s eta 0:00:02
   ---- ----------------------------------- 1.9/15.5 MB 10.0 MB/s eta 0:00:02
   ----- ---------------------------------- 2.3/15.5 MB 9.7 MB/s eta 0:00:02
   ------ --------------------------------- 2.4/15.5 MB 8.6 MB/s eta 0:00:02
   ------- -------------------------------- 3.0/15.5 MB 9.5 MB/s eta 0:00:02
   --------- ------------------------------ 3.5/15.5 MB 9.7 MB/s eta 0:00:02
   ---------- ----------------------------- 4.0/15.5 MB 9.9 MB/s eta 0:00:02
   

In [1]:
import torch
import numpy as np 

#torch from list and numpy

data= [[1,2],[3,4]]
x_data = torch.tensor(data)
print(x_data)
np_data = np.array(data)
x_np = torch.from_numpy(np_data)
print(x_np)


tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [3]:
#torch and initialize and info

shape = (2,3,)
rand_tensor = torch.rand(shape)
one_tensor = torch.ones(shape)
zero_tensor = torch.zeros(shape)

print(f"Random T : \n {rand_tensor} \n")
print(f"one_tensor  : \n {one_tensor} \n")
print(f"zero_tensor : \n {zero_tensor} \n")

print(rand_tensor.shape)
print(rand_tensor.dtype)
print(rand_tensor.device)

if(torch.cuda.is_available()):
    print("torch available")


Random T : 
 tensor([[0.5487, 0.5626, 0.7856],
        [0.8320, 0.3870, 0.8854]]) 

one_tensor  : 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

zero_tensor : 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 

torch.Size([2, 3])
torch.float32
cpu


In [9]:
#tensor and slicing and spread

tensor = torch.ones(4,4)
print('first row: ',tensor[0])
print('first col: ',tensor[:,0])
print('last col: ',tensor[...,-1])

tensor[:,1]=0
print(tensor)
#cat tensors
t1 = torch.cat([tensor,tensor,tensor])
print(t1)


# tensor ops
#행렬곱
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(tensor)
torch.matmul(tensor,tensor.T,out=y3)
print(f"y1 : {y1}\n y2 : {y2}\n y3 : {y3}\n")
#elementwise 곱
y1 = tensor * tensor
y2 = tensor.mul(tensor.T)
y3 = torch.rand_like(tensor)
torch.mul(tensor,tensor.T,out=y3)
print(f"y1 : {y1}\n y2 : {y2}\n y3 : {y3}\n")


first row:  tensor([1., 1., 1., 1.])
first col:  tensor([1., 1., 1., 1.])
last col:  tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
y1 : tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
 y2 : tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
 y3 : tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

y1 : tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
 y2 : tensor([[1., 0., 1., 1.

In [14]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item,agg)

print(tensor.add_(5))

n = np.ones(5)
t = torch.from_numpy(n)

np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")


92.0 tensor(92.)
tensor([[11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.]])
t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


In [2]:
import torch
#0을 할당
zeros = torch.zeros(3,4)
#그냥 비워둠 출력하면 그자리에 있던 값 나옴
empty = torch.empty(3,4)
print(zeros,empty)

torch.rand(3,4)

a = torch.ones((2, 3), dtype=torch.int16)
print(a)


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]) tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
